app: mytest
shortname: mytst
team: team
env: prd
ingress:
  host: mytest.dev.entur.io
  trafficType: api
container:
  image: eu.gcr.io/example:latest
  cpu: 1
  memory: 128
  replicas: 1
  maxReplicas: 5
  minAvailable: 50%
  envFrom:
    - name: hei
  env:
    - name: TEST
      value: test
  volumeMounts:
    - name: test
  volumes:
    - name: test
postgres:
  enabled: true
  cpu: 0.5
  memory: 32
configmap:
  enabled: true
  toEnv: true
  data:
    TEST: hello
