{{- if .Values.configmap.enabled }}
  {{- /* Rules */}}
  {{- $data := .Values.configmap.data | required ".Values.common.configmap.data is required." -}}
{{- /* YAML Spec */}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- toYaml $data | nindent 2 }}
{{- end }}
